### ISSUE TITLE
View:unload

### ISSUE THREAD

**Issue by rolandovillarreal** [dash14/v-network-graph#24]
Hi dash,
I don't know if it is just me or something that I may be using wrong. But I found that when I change between router-links and the unload event is triggered after I leave the component where the v-network-graph is loaded, two more events are triggered (zoom and pan) causing to increase the size of the nodes and move the position at the last second of the transition... is it posible to stop those events from being triggered?

![image](https://user-images.githubusercontent.com/95439600/144488451-61f4dc4d-cbff-4b07-af1f-6b61ff3b2c8f.png)

**Comment by dash14** [comment]
Hi @rolandovillarreal,

Thanks for your report.
I have checked the load/unload state handling and fixed the problem. ([v0.3.9](https://github.com/dash14/v-network-graph/releases))
Please check it out.

Best Regards

**Comment by John-Boik** [comment]
I am having a problem that might be related. I have updated to v0.3.9, but that did not fix the problem. 

Suppose I have a blank SVG and I use my drag and drop functions to create a node at a desired location, say, (-200,-200). I can verify the location by printing layouts.nodes to the console. Now, if I click on the node, it is highlighted as expected and the value of layouts.nodes does not change. However, pan must occur because the screen changes so that the node shifts to the center of the SVG. This happens every time I create a new node and click on it---the set of nodes becomes centered on the SVG.

None of my functions are calling pan. Is there some function in v-network-graph that is doing so after a node is clicked?

**Comment by rolandovillarreal** [comment]
Thank you for your prompt response

The validation with the status == 2 indeed solved the problem of triggering events after unload, but the behavior is still present for me. I thought that by preventing those events being triggered the unexpected "grow/fit" of the graph will be solved

Please find enclosed a short video of how the unload event even without those extra events that previously were and now are not present still update the v-network-graph (second 11 &12 of the video)

https://user-images.githubusercontent.com/95439600/144667141-52ef50ca-e7f8-4c45-b58d-6b7f3ffc9a3b.mp4

**Comment by dash14** [comment]
Hi @rolandovillarreal,

Thank you for the detailed information.
I was able to reproduce the problem as well.

The reason was that the library I was using to implement SVG pan/zoom was resetting pan and zoom on destroy.
I have seen that changing this behavior fixes the problem.
Please try [v0.3.10](https://github.com/dash14/v-network-graph/releases/tag/v0.3.10).

**Comment by rolandovillarreal** [comment]
Thank you Dash, You made it look easy!
Have an excellent weekend
