### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by automated-tester** [dash14/v-network-graph#4]
Hi, this project looks super useful for what I need to do. Unfortunately, I've tried adding it to my project and to brand new Vue projects and it always hangs on the `npm install v-network-graph`. Is this an issue with the npm registry? With my end? If so, do you know how to fix this?

Here's the output of install verbose:
```
$ npm install v-network-graph --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',      
npm verb cli   '/usr/bin/npm',       
npm verb cli   'install',
npm verb cli   'v-network-graph',    
npm verb cli   '--verbose' ]
npm info using npm@6.14.4
npm info using node@v10.19.0
npm verb npm-session 394b41768a22dfca
npm timing stage:loadCurrentTree Completed in 1606ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 20ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 584ms
npm http fetch GET 304 https://registry.npmjs.org/mitt 391ms (from cache)
[..................] / fetchMetadata: http fetch GET 304 https://registry.npmjs.org/mitt 391ms (from cache)
```

**Comment by dash14** [comment]
Hi @automated-tester,

Thanks for trying to use v-network-graph!
Hmm, it doesn't seem to be a problem on the library side, since it happens when downloading from the repository.

You may have already tried this, but according to [this page](https://stackoverflow.com/questions/37860219/npm-gets-stuck-on-fetchmetadata-network), the following command may solve the problem.
```sh
npm config set registry="http://registry.npmjs.org"
````
Also, check your proxy settings, since it seems that http proxies are sometimes the cause. (Please refer to the link above for more information.)

**Comment by automated-tester** [comment]
Hmm, it still hangs when I change the registry and it gives me more errors that it's insecure.
I don't have any proxies set up through npm.

Since this isn't an issue on your end I'll close this here and look elsewhere.
Thanks for the help though!

**Comment by dash14** [comment]
I'm sorry I can't be of more help.
I hope it will be resolved.
