### ISSUE TITLE
Mindmap functionality

### ISSUE THREAD

**Issue by ZiadJ** [dash14/v-network-graph#46]
It seems like a solid ground to implement mindmap functionality with advanced features eventually. Is that on the roadmap somehow?

**Comment by dash14** [comment]
Hi @ZiadJ,
Thank you for your comments.
Since v-network-graph is only a library for visualizing graph structures, there are no plans to develop features that will be used only for mindmap.
However, if there are specific suggestions or pull requests for features that are lacking in the mind map implementation, I would consider implementing them if they are basic features that would be useful in other types of applications.

Best Regards,
