### ISSUE TITLE
view:click event stops working after view:contextmenu

### ISSUE THREAD

**Issue by violent-boomerang** [dash14/v-network-graph#47]
Hello!
Using the [capture all events example](https://dash14.github.io/v-network-graph/examples/event.html#capture-all-events) I can see the view:click and view:dblclick events work. Then if I do a right click/long press on the view I can see view:contextmenu event work. But after that both view:click and view:dblclick are not fired anymore.

Thank you and Best Regards

**Comment by dash14** [comment]
Hi @violent-boomerang,
This issue was not seen in touch emulation using a PC browser, but could be reproduced on an actual mobile device. Thank you so much for your report.
It is now fixed and released, so please check it out. ([v0.5.8](https://github.com/dash14/v-network-graph/releases/tag/v0.5.8))

Best Regards

**Comment by violent-boomerang** [comment]
great, fixed. Thank you very much!
